//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AccountViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<DSS.Data.Models.Entities.Account>
    {
    	
    			public virtual int AccountID { get; set; }
    			public virtual int BrandID { get; set; }
    			public virtual Nullable<bool> isActive { get; set; }
    			public virtual Nullable<int> RoleID { get; set; }
    			public virtual string Username { get; set; }
    			public virtual string Password { get; set; }
    			public virtual string Fullname { get; set; }
    			public virtual string CreateDatetime { get; set; }
    	
    	public AccountViewModel() : base() { }
    	public AccountViewModel(DSS.Data.Models.Entities.Account entity) : base(entity) { }
    
    }
}
