//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class AreaViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Wisky.Data.Models.Entities.Area>
    {
    	
    			public virtual int AreaID { get; set; }
    			public virtual int LayoutID { get; set; }
    			public virtual int AreaCode { get; set; }
    			public virtual double X1Position { get; set; }
    			public virtual double X2Position { get; set; }
    			public virtual double Y1Position { get; set; }
    			public virtual double Y2Postition { get; set; }
    			public virtual string Note { get; set; }
    	
    	public AreaViewModel() : base() { }
    	public AreaViewModel(Wisky.Data.Models.Entities.Area entity) : base(entity) { }
    
    }
}
