//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class BoxViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<DSS.Data.Models.Entities.Box>
    {
    	
    			public virtual int BoxID { get; set; }
    			public virtual int LocationID { get; set; }
    			public virtual byte[] BoxName { get; set; }
    			public virtual string Description { get; set; }
    	
    	public BoxViewModel() : base() { }
    	public BoxViewModel(DSS.Data.Models.Entities.Box entity) : base(entity) { }
    
    }
}
