//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaTypeViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Wisky.Data.Models.Entities.MediaType>
    {
    	
    			public virtual int TypeID { get; set; }
    			public virtual string Name { get; set; }
    			public virtual string Description { get; set; }
    	
    	public MediaTypeViewModel() : base() { }
    	public MediaTypeViewModel(Wisky.Data.Models.Entities.MediaType entity) : base(entity) { }
    
    }
}
