//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaSrcViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Wisky.Data.Models.Entities.MediaSrc>
    {
    	
    			public virtual int MediaSrcID { get; set; }
    			public virtual int BrandID { get; set; }
    			public virtual string Title { get; set; }
    			public virtual Nullable<bool> Status { get; set; }
    			public virtual int TypeID { get; set; }
    			public virtual string URL { get; set; }
    			public virtual string UpdateDatetime { get; set; }
    			public virtual string CreateDatetime { get; set; }
    			public virtual string Description { get; set; }
    	
    	public MediaSrcViewModel() : base() { }
    	public MediaSrcViewModel(Wisky.Data.Models.Entities.MediaSrc entity) : base(entity) { }
    
    }
}
