//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlaylistItemViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<DSS.Data.Models.Entities.PlaylistItem>
    {
    	
    			public virtual int PlaylistItemID { get; set; }
    			public virtual int MediaSrcID { get; set; }
    			public virtual int PlaylistID { get; set; }
    			public virtual int DisplayOrder { get; set; }
    			public virtual string Duration { get; set; }
    	
    	public PlaylistItemViewModel() : base() { }
    	public PlaylistItemViewModel(DSS.Data.Models.Entities.PlaylistItem entity) : base(entity) { }
    
    }
}
