//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResolutionViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Wisky.Data.Models.Entities.Resolution>
    {
    	
    			public virtual int ResolutionID { get; set; }
    			public virtual double Width { get; set; }
    			public virtual double Height { get; set; }
    			public virtual string Note { get; set; }
    	
    	public ResolutionViewModel() : base() { }
    	public ResolutionViewModel(Wisky.Data.Models.Entities.Resolution entity) : base(entity) { }
    
    }
}
