//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoleViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<Wisky.Data.Models.Entities.Role>
    {
    	
    			public virtual int RoleID { get; set; }
    			public virtual string RoleName { get; set; }
    			public virtual string Description { get; set; }
    	
    	public RoleViewModel() : base() { }
    	public RoleViewModel(Wisky.Data.Models.Entities.Role entity) : base(entity) { }
    
    }
}
