//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.ViewModels
{
    using System;
    using System.Collections.Generic;
    
    public partial class ScreenViewModel : SkyWeb.DatVM.Mvc.BaseEntityViewModel<DSS.Data.Models.Entities.Screen>
    {
    	
    			public virtual int ScreenID { get; set; }
    			public virtual int LocationID { get; set; }
    			public virtual int ResolutionID { get; set; }
    			public virtual string ScreenName { get; set; }
    			public virtual string Description { get; set; }
    	
    	public ScreenViewModel() : base() { }
    	public ScreenViewModel(DSS.Data.Models.Entities.Screen entity) : base(entity) { }
    
    }
}
