//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class CreateInteractionPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CreateInteractionPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DSS.ResourcesLanguage.CreateInteractionPage", typeof(CreateInteractionPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ads Name.
        /// </summary>
        public static string AdsName {
            get {
                return ResourceManager.GetString("AdsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Setting.
        /// </summary>
        public static string AdvanceSetting {
            get {
                return ResourceManager.GetString("AdvanceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android device.
        /// </summary>
        public static string AndroidDevice {
            get {
                return ResourceManager.GetString("AndroidDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Android application URL.
        /// </summary>
        public static string AndroidUrl {
            get {
                return ResourceManager.GetString("AndroidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Install.
        /// </summary>
        public static string AppInstall {
            get {
                return ResourceManager.GetString("AppInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Content.
        /// </summary>
        public static string ApplicationContent {
            get {
                return ResourceManager.GetString("ApplicationContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Url.
        /// </summary>
        public static string ApplicationUrl {
            get {
                return ResourceManager.GetString("ApplicationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background for mobile.
        /// </summary>
        public static string BackgroundForMobile {
            get {
                return ResourceManager.GetString("BackgroundForMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background for PC.
        /// </summary>
        public static string BackgroundForPC {
            get {
                return ResourceManager.GetString("BackgroundForPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Image.
        /// </summary>
        public static string BackgroundImage {
            get {
                return ResourceManager.GetString("BackgroundImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Location.
        /// </summary>
        public static string ChooseLocation {
            get {
                return ResourceManager.GetString("ChooseLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interaction Page.
        /// </summary>
        public static string CIP {
            get {
                return ResourceManager.GetString("CIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Website.
        /// </summary>
        public static string ClickWebsite {
            get {
                return ResourceManager.GetString("ClickWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable Connect Button:.
        /// </summary>
        public static string ConnectButton {
            get {
                return ResourceManager.GetString("ConnectButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interaction Page.
        /// </summary>
        public static string CreateInteraction {
            get {
                return ResourceManager.GetString("CreateInteraction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Interaction Page successfully.
        /// </summary>
        public static string CreateInteractionPageSuccess {
            get {
                return ResourceManager.GetString("CreateInteractionPageSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Parting.
        /// </summary>
        public static string DayParting {
            get {
                return ResourceManager.GetString("DayParting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Detail Information.
        /// </summary>
        public static string DetailInformation {
            get {
                return ResourceManager.GetString("DetailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Filter.
        /// </summary>
        public static string DeviceFilter {
            get {
                return ResourceManager.GetString("DeviceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do Survey.
        /// </summary>
        public static string DoSurvey {
            get {
                return ResourceManager.GetString("DoSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration (s).
        /// </summary>
        public static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable checkin.
        /// </summary>
        public static string EnableCheckin {
            get {
                return ResourceManager.GetString("EnableCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook ID:.
        /// </summary>
        public static string FacebookID {
            get {
                return ResourceManager.GetString("FacebookID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook like Invitation:.
        /// </summary>
        public static string FacebookLikeInvitation {
            get {
                return ResourceManager.GetString("FacebookLikeInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From - To.
        /// </summary>
        public static string FromTo {
            get {
                return ResourceManager.GetString("FromTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Infomation.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get Offer.
        /// </summary>
        public static string GetOffer {
            get {
                return ResourceManager.GetString("GetOffer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google form url:.
        /// </summary>
        public static string GoogleFormUrl {
            get {
                return ResourceManager.GetString("GoogleFormUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High (Monthly).
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Parting.
        /// </summary>
        public static string HourParting {
            get {
                return ResourceManager.GetString("HourParting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interaction Page name.
        /// </summary>
        public static string InteractionPageName {
            get {
                return ResourceManager.GetString("InteractionPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS device.
        /// </summary>
        public static string IosDevice {
            get {
                return ResourceManager.GetString("IosDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to iOS application URL.
        /// </summary>
        public static string IosUrl {
            get {
                return ResourceManager.GetString("IosUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Like Facebook.
        /// </summary>
        public static string LikeFacebook {
            get {
                return ResourceManager.GetString("LikeFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations Use This.
        /// </summary>
        public static string LocationsUseThis {
            get {
                return ResourceManager.GetString("LocationsUseThis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Long Survey.
        /// </summary>
        public static string LongSurvey {
            get {
                return ResourceManager.GetString("LongSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low (Daily).
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium (Weekly).
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message:.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Location.
        /// </summary>
        public static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offer detail:.
        /// </summary>
        public static string OfferDetail {
            get {
                return ResourceManager.GetString("OfferDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Inject.
        /// </summary>
        public static string PageInject {
            get {
                return ResourceManager.GetString("PageInject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Inject Url:.
        /// </summary>
        public static string PageInjectUrl {
            get {
                return ResourceManager.GetString("PageInjectUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select From Directory.
        /// </summary>
        public static string SelectFromDirectory {
            get {
                return ResourceManager.GetString("SelectFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Short Survey.
        /// </summary>
        public static string ShortSurvey {
            get {
                return ResourceManager.GetString("ShortSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success button text.
        /// </summary>
        public static string SuccessButtonText {
            get {
                return ResourceManager.GetString("SuccessButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey question:.
        /// </summary>
        public static string SurveyQuestion {
            get {
                return ResourceManager.GetString("SurveyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Survey type:.
        /// </summary>
        public static string SurveyType {
            get {
                return ResourceManager.GetString("SurveyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video description:.
        /// </summary>
        public static string VideoDescription {
            get {
                return ResourceManager.GetString("VideoDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video link:.
        /// </summary>
        public static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch Video.
        /// </summary>
        public static string WatchVideo {
            get {
                return ResourceManager.GetString("WatchVideo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Address:.
        /// </summary>
        public static string WebsiteAddress {
            get {
                return ResourceManager.GetString("WebsiteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website Introdution:.
        /// </summary>
        public static string WebsiteIntrodution {
            get {
                return ResourceManager.GetString("WebsiteIntrodution", resourceCulture);
            }
        }
    }
}
