//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class DisplayAdmin {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DisplayAdmin() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wisky.ResourcesLanguage.DisplayAdmin", typeof(DisplayAdmin).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Date.
        /// </summary>
        public static string ActiveDate {
            get {
                return ResourceManager.GetString("ActiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Display.
        /// </summary>
        public static string AddDisplay {
            get {
                return ResourceManager.GetString("AddDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Display Type.
        /// </summary>
        public static string AddDisplayType {
            get {
                return ResourceManager.GetString("AddDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Resolution.
        /// </summary>
        public static string AddResolution {
            get {
                return ResourceManager.GetString("AddResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Display.
        /// </summary>
        public static string CreateDisplay {
            get {
                return ResourceManager.GetString("CreateDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Display Type.
        /// </summary>
        public static string CreateDisplayType {
            get {
                return ResourceManager.GetString("CreateDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Resolution.
        /// </summary>
        public static string CreateResolution {
            get {
                return ResourceManager.GetString("CreateResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name*.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Type.
        /// </summary>
        public static string DisplayType {
            get {
                return ResourceManager.GetString("DisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Type*.
        /// </summary>
        public static string DisplayTypeHead {
            get {
                return ResourceManager.GetString("DisplayTypeHead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Type Name.
        /// </summary>
        public static string DisplayTypeName {
            get {
                return ResourceManager.GetString("DisplayTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Display.
        /// </summary>
        public static string EditDisplay {
            get {
                return ResourceManager.GetString("EditDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Display Type.
        /// </summary>
        public static string EditDisplayType {
            get {
                return ResourceManager.GetString("EditDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Resolution.
        /// </summary>
        public static string EditResolution {
            get {
                return ResourceManager.GetString("EditResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is Actived*.
        /// </summary>
        public static string IsActived {
            get {
                return ResourceManager.GetString("IsActived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location*.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Display.
        /// </summary>
        public static string ManageDisplay {
            get {
                return ResourceManager.GetString("ManageDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Display Type.
        /// </summary>
        public static string ManageDisplayType {
            get {
                return ResourceManager.GetString("ManageDisplayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Resolution.
        /// </summary>
        public static string ManageResolution {
            get {
                return ResourceManager.GetString("ManageResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resolution Name.
        /// </summary>
        public static string ResolutionName {
            get {
                return ResourceManager.GetString("ResolutionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
