//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LoginPage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LoginPage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wisky.ResourcesLanguage.LoginPage", typeof(LoginPage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Without Pass.
        /// </summary>
        public static string AccountWithoutPass {
            get {
                return ResourceManager.GetString("AccountWithoutPass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Information.
        /// </summary>
        public static string AddInformation {
            get {
                return ResourceManager.GetString("AddInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional info.
        /// </summary>
        public static string AdditionalInfo {
            get {
                return ResourceManager.GetString("AdditionalInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddSuccessful.
        /// </summary>
        public static string AddSuccessful {
            get {
                return ResourceManager.GetString("AddSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Setting.
        /// </summary>
        public static string AdvanceSetting {
            get {
                return ResourceManager.GetString("AdvanceSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising mode.
        /// </summary>
        public static string AdvertisingMode {
            get {
                return ResourceManager.GetString("AdvertisingMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising Report Chart.
        /// </summary>
        public static string AdvertisingReportChart {
            get {
                return ResourceManager.GetString("AdvertisingReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Location.
        /// </summary>
        public static string AllLocation {
            get {
                return ResourceManager.GetString("AllLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Laptop.
        /// </summary>
        public static string Background {
            get {
                return ResourceManager.GetString("Background", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Mobile.
        /// </summary>
        public static string BackgroundMobile {
            get {
                return ResourceManager.GetString("BackgroundMobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Logo.
        /// </summary>
        public static string BrandLogo {
            get {
                return ResourceManager.GetString("BrandLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser Report Chart.
        /// </summary>
        public static string BrowserReportChart {
            get {
                return ResourceManager.GetString("BrowserReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Color.
        /// </summary>
        public static string ButtonBackgroundColor {
            get {
                return ResourceManager.GetString("ButtonBackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Color.
        /// </summary>
        public static string ButtonTextColor {
            get {
                return ResourceManager.GetString("ButtonTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bypass Login Page.
        /// </summary>
        public static string ByPassLoginPage {
            get {
                return ResourceManager.GetString("ByPassLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chinese.
        /// </summary>
        public static string Chinese {
            get {
                return ResourceManager.GetString("Chinese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Through.
        /// </summary>
        public static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer could give their info and click Next to gain access to the Internet..
        /// </summary>
        public static string ClickThroughTooltip {
            get {
                return ResourceManager.GetString("ClickThroughTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Contact Information.
        /// </summary>
        public static string ContactMode {
            get {
                return ResourceManager.GetString("ContactMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Login page.
        /// </summary>
        public static string CreateLandingPage {
            get {
                return ResourceManager.GetString("CreateLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Matching.
        /// </summary>
        public static string DataMatching {
            get {
                return ResourceManager.GetString("DataMatching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day Parting.
        /// </summary>
        public static string DayParting {
            get {
                return ResourceManager.GetString("DayParting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete this login page.
        /// </summary>
        public static string DeleteLoginPageTip {
            get {
                return ResourceManager.GetString("DeleteLoginPageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location or Device was not applied.
        /// </summary>
        public static string DemoError {
            get {
                return ResourceManager.GetString("DemoError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attributes On Desktop.
        /// </summary>
        public static string DesktopFormAttributes {
            get {
                return ResourceManager.GetString("DesktopFormAttributes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desktop Form Ordinate.
        /// </summary>
        public static string DesktopFormOrdinate {
            get {
                return ResourceManager.GetString("DesktopFormOrdinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Filter.
        /// </summary>
        public static string DeviceFilter {
            get {
                return ResourceManager.GetString("DeviceFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Report Chart.
        /// </summary>
        public static string DeviceReportChart {
            get {
                return ResourceManager.GetString("DeviceReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Displayed Infomation.
        /// </summary>
        public static string DisplayedInfomation {
            get {
                return ResourceManager.GetString("DisplayedInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Infomation.
        /// </summary>
        public static string DisplayInfomation {
            get {
                return ResourceManager.GetString("DisplayInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit login page.
        /// </summary>
        public static string EditLoginPageTip {
            get {
                return ResourceManager.GetString("EditLoginPageTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EditSuccessful.
        /// </summary>
        public static string EditSuccessful {
            get {
                return ResourceManager.GetString("EditSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data record.
        /// </summary>
        public static string EmptyTable {
            get {
                return ResourceManager.GetString("EmptyTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter e-mail.
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Page Url.
        /// </summary>
        public static string EnterPageUrl {
            get {
                return ResourceManager.GetString("EnterPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string EnterPhoneNumber {
            get {
                return ResourceManager.GetString("EnterPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Checkin.
        /// </summary>
        public static string FacebookCheckin {
            get {
                return ResourceManager.GetString("FacebookCheckin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field.
        /// </summary>
        public static string Field {
            get {
                return ResourceManager.GetString("Field", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed password.
        /// </summary>
        public static string Fixed {
            get {
                return ResourceManager.GetString("Fixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fixed Advertising.
        /// </summary>
        public static string FixedAdvertising {
            get {
                return ResourceManager.GetString("FixedAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Infomation.
        /// </summary>
        public static string GeneralInfomation {
            get {
                return ResourceManager.GetString("GeneralInfomation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Generate {
            get {
                return ResourceManager.GetString("Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Random Password.
        /// </summary>
        public static string GenerateRandomPassword {
            get {
                return ResourceManager.GetString("GenerateRandomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google.
        /// </summary>
        public static string Google {
            get {
                return ResourceManager.GetString("Google", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hour Parting.
        /// </summary>
        public static string HourParting {
            get {
                return ResourceManager.GetString("HourParting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If user has already logged in.
        /// </summary>
        public static string IfUserHasLogin {
            get {
                return ResourceManager.GetString("IfUserHasLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Showing _START_ to _END_ of _TOTAL_ entries.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input Password.
        /// </summary>
        public static string InputPassword {
            get {
                return ResourceManager.GetString("InputPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login page.
        /// </summary>
        public static string InteractionPage {
            get {
                return ResourceManager.GetString("InteractionPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page not existed.
        /// </summary>
        public static string InteractionPageFail {
            get {
                return ResourceManager.GetString("InteractionPageFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IsActive.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Japanese.
        /// </summary>
        public static string Japanese {
            get {
                return ResourceManager.GetString("Japanese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show _MENU_ entries.
        /// </summary>
        public static string LengthMenu {
            get {
                return ResourceManager.GetString("LengthMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Settings.
        /// </summary>
        public static string LocationSetting {
            get {
                return ResourceManager.GetString("LocationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location which use this login page.
        /// </summary>
        public static string LocationUsage {
            get {
                return ResourceManager.GetString("LocationUsage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Flow.
        /// </summary>
        public static string LoginFlow {
            get {
                return ResourceManager.GetString("LoginFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Mode.
        /// </summary>
        public static string LoginMode {
            get {
                return ResourceManager.GetString("LoginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Control.
        /// </summary>
        public static string LoginModeOfCustom {
            get {
                return ResourceManager.GetString("LoginModeOfCustom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page 2.
        /// </summary>
        public static string LoginPage2 {
            get {
                return ResourceManager.GetString("LoginPage2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login page name.
        /// </summary>
        public static string LoginPageName {
            get {
                return ResourceManager.GetString("LoginPageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Page.
        /// </summary>
        public static string LoginPages {
            get {
                return ResourceManager.GetString("LoginPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Report Chart.
        /// </summary>
        public static string LoginReportChart {
            get {
                return ResourceManager.GetString("LoginReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Text.
        /// </summary>
        public static string LoginText {
            get {
                return ResourceManager.GetString("LoginText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with random password.
        /// </summary>
        public static string LoginWithRandomPassword {
            get {
                return ResourceManager.GetString("LoginWithRandomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locations which use this login page.
        /// </summary>
        public static string LWUseLP {
            get {
                return ResourceManager.GetString("LWUseLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Account.
        /// </summary>
        public static string MAccount {
            get {
                return ResourceManager.GetString("MAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer could login with a given account..
        /// </summary>
        public static string MAccountTooltip {
            get {
                return ResourceManager.GetString("MAccountTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manual.
        /// </summary>
        public static string Manual {
            get {
                return ResourceManager.GetString("Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        public static string Medium {
            get {
                return ResourceManager.GetString("Medium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Membership.
        /// </summary>
        public static string Membership {
            get {
                return ResourceManager.GetString("Membership", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Form Ordinate.
        /// </summary>
        public static string MobileFormOrdinate {
            get {
                return ResourceManager.GetString("MobileFormOrdinate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Click Through.
        /// </summary>
        public static string ModeClick {
            get {
                return ResourceManager.GetString("ModeClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi Language.
        /// </summary>
        public static string MultiLanguage {
            get {
                return ResourceManager.GetString("MultiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New login page.
        /// </summary>
        public static string NewLoginPage {
            get {
                return ResourceManager.GetString("NewLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No..
        /// </summary>
        public static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One time password.
        /// </summary>
        public static string OneTime {
            get {
                return ResourceManager.GetString("OneTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login by Social Network.
        /// </summary>
        public static string OpenLogin {
            get {
                return ResourceManager.GetString("OpenLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OS Report Chart.
        /// </summary>
        public static string OSReportChart {
            get {
                return ResourceManager.GetString("OSReportChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Title.
        /// </summary>
        public static string PageTitle {
            get {
                return ResourceManager.GetString("PageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing.
        /// </summary>
        public static string Processing {
            get {
                return ResourceManager.GetString("Processing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random Password.
        /// </summary>
        public static string RandomPassword {
            get {
                return ResourceManager.GetString("RandomPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Địa chỉ.
        /// </summary>
        public static string RegisterAddress {
            get {
                return ResourceManager.GetString("RegisterAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary.
        /// </summary>
        public static string RegisterAttr {
            get {
                return ResourceManager.GetString("RegisterAttr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary 1.
        /// </summary>
        public static string RegisterAttr1 {
            get {
                return ResourceManager.GetString("RegisterAttr1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary 2.
        /// </summary>
        public static string RegisterAttr2 {
            get {
                return ResourceManager.GetString("RegisterAttr2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary 3.
        /// </summary>
        public static string RegisterAttr3 {
            get {
                return ResourceManager.GetString("RegisterAttr3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary 4.
        /// </summary>
        public static string RegisterAttr4 {
            get {
                return ResourceManager.GetString("RegisterAttr4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ancillary 5.
        /// </summary>
        public static string RegisterAttr5 {
            get {
                return ResourceManager.GetString("RegisterAttr5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required.
        /// </summary>
        public static string RegisterAttrIsRequired {
            get {
                return ResourceManager.GetString("RegisterAttrIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2_Title_Value1|Value2|Value3|Value4.
        /// </summary>
        public static string RegisterAttrPlaceholder {
            get {
                return ResourceManager.GetString("RegisterAttrPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Day.
        /// </summary>
        public static string RegisterBirthDay {
            get {
                return ResourceManager.GetString("RegisterBirthDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job.
        /// </summary>
        public static string RegisterJob {
            get {
                return ResourceManager.GetString("RegisterJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full name.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organization.
        /// </summary>
        public static string RegisterOrganization {
            get {
                return ResourceManager.GetString("RegisterOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number phone.
        /// </summary>
        public static string RegisterPhone {
            get {
                return ResourceManager.GetString("RegisterPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string RegisterPosition {
            get {
                return ResourceManager.GetString("RegisterPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveInformation {
            get {
                return ResourceManager.GetString("RemoveInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required Click Advertisement.
        /// </summary>
        public static string RequiredClickAdvertisement {
            get {
                return ResourceManager.GetString("RequiredClickAdvertisement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Welcome Text.
        /// </summary>
        public static string ReturnWelcomeText {
            get {
                return ResourceManager.GetString("ReturnWelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Russian.
        /// </summary>
        public static string Russian {
            get {
                return ResourceManager.GetString("Russian", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Changes.
        /// </summary>
        public static string SaveChanges {
            get {
                return ResourceManager.GetString("SaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule.
        /// </summary>
        public static string Schedule {
            get {
                return ResourceManager.GetString("Schedule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seismic Intensity.
        /// </summary>
        public static string SeismicIntensity {
            get {
                return ResourceManager.GetString("SeismicIntensity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string SeismicValue {
            get {
                return ResourceManager.GetString("SeismicValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select file.
        /// </summary>
        public static string SelectFile {
            get {
                return ResourceManager.GetString("SelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select From Directory.
        /// </summary>
        public static string SelectFromDirectory {
            get {
                return ResourceManager.GetString("SelectFromDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Template.
        /// </summary>
        public static string SelectTemplate {
            get {
                return ResourceManager.GetString("SelectTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send pass by.
        /// </summary>
        public static string SendPassBy {
            get {
                return ResourceManager.GetString("SendPassBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session duration.
        /// </summary>
        public static string SessionDuration {
            get {
                return ResourceManager.GetString("SessionDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set customer&apos;s intake info.
        /// </summary>
        public static string SetCustomerInfo {
            get {
                return ResourceManager.GetString("SetCustomerInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Advertising.
        /// </summary>
        public static string ShowAdvertising {
            get {
                return ResourceManager.GetString("ShowAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Login Page.
        /// </summary>
        public static string ShowLoginPage {
            get {
                return ResourceManager.GetString("ShowLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show other Login Page.
        /// </summary>
        public static string ShowOtherLoginPage {
            get {
                return ResourceManager.GetString("ShowOtherLoginPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show register info.
        /// </summary>
        public static string ShowRegisterInfo {
            get {
                return ResourceManager.GetString("ShowRegisterInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS.
        /// </summary>
        public static string SMS {
            get {
                return ResourceManager.GetString("SMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SMS Password.
        /// </summary>
        public static string SMSPassword {
            get {
                return ResourceManager.GetString("SMSPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success page url.
        /// </summary>
        public static string SuccessPageUrl {
            get {
                return ResourceManager.GetString("SuccessPageUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support Multi Language.
        /// </summary>
        public static string SupportMultiLanguage {
            get {
                return ResourceManager.GetString("SupportMultiLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to hour(s), system will.
        /// </summary>
        public static string SystemWill {
            get {
                return ResourceManager.GetString("SystemWill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text Language.
        /// </summary>
        public static string TextLanguage {
            get {
                return ResourceManager.GetString("TextLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeInformation {
            get {
                return ResourceManager.GetString("TypeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use default Brand Logo.
        /// </summary>
        public static string UseDefaultBrandLogo {
            get {
                return ResourceManager.GetString("UseDefaultBrandLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Value {
            get {
                return ResourceManager.GetString("Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value 1| Value 2.
        /// </summary>
        public static string ValuePlaceHolder {
            get {
                return ResourceManager.GetString("ValuePlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vietnamese.
        /// </summary>
        public static string Vietnamese {
            get {
                return ResourceManager.GetString("Vietnamese", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome Text.
        /// </summary>
        public static string WelcomeText {
            get {
                return ResourceManager.GetString("WelcomeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        public static string WidthFormDesktop {
            get {
                return ResourceManager.GetString("WidthFormDesktop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No suitable record found.
        /// </summary>
        public static string ZeroRecord {
            get {
                return ResourceManager.GetString("ZeroRecord", resourceCulture);
            }
        }
    }
}
