//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.ResourcesLanguage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UserStatistic {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserStatistic() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wisky.ResourcesLanguage.UserStatistic", typeof(UserStatistic).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Locations.
        /// </summary>
        public static string AllLocation {
            get {
                return ResourceManager.GetString("AllLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click Through.
        /// </summary>
        public static string ClickThrough {
            get {
                return ResourceManager.GetString("ClickThrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook.
        /// </summary>
        public static string Facebook {
            get {
                return ResourceManager.GetString("Facebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login By Date.
        /// </summary>
        public static string LoginByDate {
            get {
                return ResourceManager.GetString("LoginByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Modes.
        /// </summary>
        public static string LoginMode {
            get {
                return ResourceManager.GetString("LoginMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Success.
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Users.
        /// </summary>
        public static string NewUser {
            get {
                return ResourceManager.GetString("NewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoLocation.
        /// </summary>
        public static string NoLocation {
            get {
                return ResourceManager.GetString("NoLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old User.
        /// </summary>
        public static string OldUser {
            get {
                return ResourceManager.GetString("OldUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate.
        /// </summary>
        public static string Rate {
            get {
                return ResourceManager.GetString("Rate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The percentage of user logins (Total login/Total view)..
        /// </summary>
        public static string RateTitle {
            get {
                return ResourceManager.GetString("RateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return.
        /// </summary>
        public static string Return {
            get {
                return ResourceManager.GetString("Return", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Return Users.
        /// </summary>
        public static string ReturnUser {
            get {
                return ResourceManager.GetString("ReturnUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total logins (using Facebook/Google/Password)..
        /// </summary>
        public static string TotalLogin {
            get {
                return ResourceManager.GetString("TotalLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total new users of your locations..
        /// </summary>
        public static string TotalNewTitle {
            get {
                return ResourceManager.GetString("TotalNewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total visits of return users of your locations..
        /// </summary>
        public static string TotalReturnTitle {
            get {
                return ResourceManager.GetString("TotalReturnTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users Login.
        /// </summary>
        public static string TotalUsersLogin {
            get {
                return ResourceManager.GetString("TotalUsersLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Users Visit.
        /// </summary>
        public static string TotalUsersVisit {
            get {
                return ResourceManager.GetString("TotalUsersVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total view.
        /// </summary>
        public static string TotalView {
            get {
                return ResourceManager.GetString("TotalView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total views of landing page..
        /// </summary>
        public static string TotalViewTitle {
            get {
                return ResourceManager.GetString("TotalViewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total visit.
        /// </summary>
        public static string TotalVisit {
            get {
                return ResourceManager.GetString("TotalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total visits to your locations..
        /// </summary>
        public static string TotalVisitTitle {
            get {
                return ResourceManager.GetString("TotalVisitTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Analysis.
        /// </summary>
        public static string UserAnalysis {
            get {
                return ResourceManager.GetString("UserAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User By Date.
        /// </summary>
        public static string UserByDate {
            get {
                return ResourceManager.GetString("UserByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Login Overview.
        /// </summary>
        public static string UserLoginOverview {
            get {
                return ResourceManager.GetString("UserLoginOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Overview.
        /// </summary>
        public static string UserOverview {
            get {
                return ResourceManager.GetString("UserOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visit by day.
        /// </summary>
        public static string VisitByDay {
            get {
                return ResourceManager.GetString("VisitByDay", resourceCulture);
            }
        }
    }
}
