//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class MediaSrc
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MediaSrc()
        {
            this.PlaylistItems = new HashSet<PlaylistItem>();
        }
    
        public int MediaSrcID { get; set; }
        public int BrandID { get; set; }
        public string Title { get; set; }
        public Nullable<bool> Status { get; set; }
        public int TypeID { get; set; }
        public string URL { get; set; }
        public string UpdateDatetime { get; set; }
        public string CreateDatetime { get; set; }
        public string Description { get; set; }
    
        public virtual Brand Brand { get; set; }
        public virtual MediaType MediaType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlaylistItem> PlaylistItems { get; set; }
    }
}
