//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAccountService : SkyWeb.DatVM.Data.IBaseService<Account>
    {
    }
    
    public partial class AccountService : SkyWeb.DatVM.Data.BaseService<Account>, IAccountService
    {
        public AccountService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAccountRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
