//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IAreaService : SkyWeb.DatVM.Data.IBaseService<Area>
    {
    }
    
    public partial class AreaService : SkyWeb.DatVM.Data.BaseService<Area>, IAreaService
    {
        public AreaService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IAreaRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
