//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IBoxService : SkyWeb.DatVM.Data.IBaseService<Box>
    {
    }
    
    public partial class BoxService : SkyWeb.DatVM.Data.BaseService<Box>, IBoxService
    {
        public BoxService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IBoxRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
