//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IDeviceScenarioService : SkyWeb.DatVM.Data.IBaseService<DeviceScenario>
    {
    }
    
    public partial class DeviceScenarioService : SkyWeb.DatVM.Data.BaseService<DeviceScenario>, IDeviceScenarioService
    {
        public DeviceScenarioService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IDeviceScenarioRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
