//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILayoutService : SkyWeb.DatVM.Data.IBaseService<Layout>
    {
    }
    
    public partial class LayoutService : SkyWeb.DatVM.Data.BaseService<Layout>, ILayoutService
    {
        public LayoutService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILayoutRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
