//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface ILocationService : SkyWeb.DatVM.Data.IBaseService<Location>
    {
    }
    
    public partial class LocationService : SkyWeb.DatVM.Data.BaseService<Location>, ILocationService
    {
        public LocationService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.ILocationRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
