//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSS.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IMediaTypeService : SkyWeb.DatVM.Data.IBaseService<MediaType>
    {
    }
    
    public partial class MediaTypeService : SkyWeb.DatVM.Data.BaseService<MediaType>, IMediaTypeService
    {
        public MediaTypeService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IMediaTypeRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
