//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPlaylistService : SkyWeb.DatVM.Data.IBaseService<Playlist>
    {
    }
    
    public partial class PlaylistService : SkyWeb.DatVM.Data.BaseService<Playlist>, IPlaylistService
    {
        public PlaylistService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPlaylistRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
