//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IPlaylistItemService : SkyWeb.DatVM.Data.IBaseService<PlaylistItem>
    {
    }
    
    public partial class PlaylistItemService : SkyWeb.DatVM.Data.BaseService<PlaylistItem>, IPlaylistItemService
    {
        public PlaylistItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IPlaylistItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
