//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IResolutionService : SkyWeb.DatVM.Data.IBaseService<Resolution>
    {
    }
    
    public partial class ResolutionService : SkyWeb.DatVM.Data.BaseService<Resolution>, IResolutionService
    {
        public ResolutionService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IResolutionRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
