//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IScenarioItemService : SkyWeb.DatVM.Data.IBaseService<ScenarioItem>
    {
    }
    
    public partial class ScenarioItemService : SkyWeb.DatVM.Data.BaseService<ScenarioItem>, IScenarioItemService
    {
        public ScenarioItemService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IScenarioItemRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
