//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IScenarioService : SkyWeb.DatVM.Data.IBaseService<Scenario>
    {
    }
    
    public partial class ScenarioService : SkyWeb.DatVM.Data.BaseService<Scenario>, IScenarioService
    {
        public ScenarioService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IScenarioRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
