//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IScreenService : SkyWeb.DatVM.Data.IBaseService<Screen>
    {
    }
    
    public partial class ScreenService : SkyWeb.DatVM.Data.BaseService<Screen>, IScreenService
    {
        public ScreenService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IScreenRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
