//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wisky.Data.Models.Entities.Services
{
    using System;
    using System.Collections.Generic;
    
    
    public partial interface IsysdiagramService : SkyWeb.DatVM.Data.IBaseService<sysdiagram>
    {
    }
    
    public partial class sysdiagramService : SkyWeb.DatVM.Data.BaseService<sysdiagram>, IsysdiagramService
    {
        public sysdiagramService(SkyWeb.DatVM.Data.IUnitOfWork unitOfWork, Repositories.IsysdiagramRepository repository) : base(unitOfWork, repository)
        {
        }
    }
}
