//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MenuItem_EN_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MenuItem_EN_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MenuItem_EN_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point.
        /// </summary>
        internal static string AccessPoint {
            get {
                return ResourceManager.GetString("AccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access point group.
        /// </summary>
        internal static string AccessPointGroup {
            get {
                return ResourceManager.GetString("AccessPointGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Accounts.
        /// </summary>
        internal static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add publisher.
        /// </summary>
        internal static string AddPublisher {
            get {
                return ResourceManager.GetString("AddPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string AdministratorRole {
            get {
                return ResourceManager.GetString("AdministratorRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertiser.
        /// </summary>
        internal static string AdvertiserRole {
            get {
                return ResourceManager.GetString("AdvertiserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertising.
        /// </summary>
        internal static string Advertising {
            get {
                return ResourceManager.GetString("Advertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand.
        /// </summary>
        internal static string Brand {
            get {
                return ResourceManager.GetString("Brand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brand Analysis.
        /// </summary>
        internal static string BrandAnalysis {
            get {
                return ResourceManager.GetString("BrandAnalysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BrandManager.
        /// </summary>
        internal static string BrandManager {
            get {
                return ResourceManager.GetString("BrandManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campaign.
        /// </summary>
        internal static string Campaign {
            get {
                return ResourceManager.GetString("Campaign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category Image.
        /// </summary>
        internal static string CategoryImage {
            get {
                return ResourceManager.GetString("CategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupon.
        /// </summary>
        internal static string Coupon {
            get {
                return ResourceManager.GetString("Coupon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create access point.
        /// </summary>
        internal static string CreateAccessPoint {
            get {
                return ResourceManager.GetString("CreateAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create advertising.
        /// </summary>
        internal static string CreateAdvertising {
            get {
                return ResourceManager.GetString("CreateAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create access point group.
        /// </summary>
        internal static string CreateAPG {
            get {
                return ResourceManager.GetString("CreateAPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand.
        /// </summary>
        internal static string CreateBrand {
            get {
                return ResourceManager.GetString("CreateBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Brand Manager.
        /// </summary>
        internal static string CreateBrandManager {
            get {
                return ResourceManager.GetString("CreateBrandManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Customer List.
        /// </summary>
        internal static string CreateCustomerList {
            get {
                return ResourceManager.GetString("CreateCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create landing app.
        /// </summary>
        internal static string CreateLandingApp {
            get {
                return ResourceManager.GetString("CreateLandingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create landing page.
        /// </summary>
        internal static string CreateLandingPage {
            get {
                return ResourceManager.GetString("CreateLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create landing template.
        /// </summary>
        internal static string CreateLandingTemplate {
            get {
                return ResourceManager.GetString("CreateLandingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create location.
        /// </summary>
        internal static string CreateLocation {
            get {
                return ResourceManager.GetString("CreateLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create publisher.
        /// </summary>
        internal static string CreatePublisher {
            get {
                return ResourceManager.GetString("CreatePublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customer List Detail.
        /// </summary>
        internal static string CustomerListDetail {
            get {
                return ResourceManager.GetString("CustomerListDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit access point.
        /// </summary>
        internal static string EditAccessPoint {
            get {
                return ResourceManager.GetString("EditAccessPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit advertising.
        /// </summary>
        internal static string EditAdvertising {
            get {
                return ResourceManager.GetString("EditAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit access point group.
        /// </summary>
        internal static string EditAPG {
            get {
                return ResourceManager.GetString("EditAPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Brand Manager.
        /// </summary>
        internal static string EditBrandManager {
            get {
                return ResourceManager.GetString("EditBrandManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Customer List.
        /// </summary>
        internal static string EditCustomerList {
            get {
                return ResourceManager.GetString("EditCustomerList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit landing page.
        /// </summary>
        internal static string EditLandingPage {
            get {
                return ResourceManager.GetString("EditLandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit landing template.
        /// </summary>
        internal static string EditLandingTemplate {
            get {
                return ResourceManager.GetString("EditLandingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit location.
        /// </summary>
        internal static string EditLocation {
            get {
                return ResourceManager.GetString("EditLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit publisher.
        /// </summary>
        internal static string EditPublisher {
            get {
                return ResourceManager.GetString("EditPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Marketing.
        /// </summary>
        internal static string EmailMarketing {
            get {
                return ResourceManager.GetString("EmailMarketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impression.
        /// </summary>
        internal static string Impression {
            get {
                return ResourceManager.GetString("Impression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing app.
        /// </summary>
        internal static string LandingApp {
            get {
                return ResourceManager.GetString("LandingApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing page.
        /// </summary>
        internal static string LandingPage {
            get {
                return ResourceManager.GetString("LandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing template.
        /// </summary>
        internal static string LandingTemplate {
            get {
                return ResourceManager.GetString("LandingTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Manager.
        /// </summary>
        internal static string LocationManager {
            get {
                return ResourceManager.GetString("LocationManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage user accounts.
        /// </summary>
        internal static string ManAccount {
            get {
                return ResourceManager.GetString("ManAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage advertising.
        /// </summary>
        internal static string ManAdvertising {
            get {
                return ResourceManager.GetString("ManAdvertising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage.
        /// </summary>
        internal static string Manage {
            get {
                return ResourceManager.GetString("Manage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Access points.
        /// </summary>
        internal static string ManAP {
            get {
                return ResourceManager.GetString("ManAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage access point group.
        /// </summary>
        internal static string ManAPG {
            get {
                return ResourceManager.GetString("ManAPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage app.
        /// </summary>
        internal static string ManApp {
            get {
                return ResourceManager.GetString("ManApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Brand.
        /// </summary>
        internal static string ManBrand {
            get {
                return ResourceManager.GetString("ManBrand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Brand Manager.
        /// </summary>
        internal static string ManBrandManager {
            get {
                return ResourceManager.GetString("ManBrandManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage category image.
        /// </summary>
        internal static string ManCategoryImage {
            get {
                return ResourceManager.GetString("ManCategoryImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage landing page.
        /// </summary>
        internal static string ManLP {
            get {
                return ResourceManager.GetString("ManLP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage publisher.
        /// </summary>
        internal static string ManPublisher {
            get {
                return ResourceManager.GetString("ManPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage landing template.
        /// </summary>
        internal static string ManTemplate {
            get {
                return ResourceManager.GetString("ManTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage vendor.
        /// </summary>
        internal static string ManVendor {
            get {
                return ResourceManager.GetString("ManVendor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presense.
        /// </summary>
        internal static string Presense {
            get {
                return ResourceManager.GetString("Presense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string Publisher {
            get {
                return ResourceManager.GetString("Publisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publisher.
        /// </summary>
        internal static string PublisherRole {
            get {
                return ResourceManager.GetString("PublisherRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report advertisments.
        /// </summary>
        internal static string RepAds {
            get {
                return ResourceManager.GetString("RepAds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report advertising.
        /// </summary>
        internal static string RepAdverstising {
            get {
                return ResourceManager.GetString("RepAdverstising", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report login.
        /// </summary>
        internal static string RepLogin {
            get {
                return ResourceManager.GetString("RepLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribers.
        /// </summary>
        internal static string Subscribers {
            get {
                return ResourceManager.GetString("Subscribers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location &amp; AccessPointGroup.
        /// </summary>
        internal static string ThumbnailList {
            get {
                return ResourceManager.GetString("ThumbnailList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
    }
}
