//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Message_EN_Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Message_EN_Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Message_EN_Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation fail! Activation Code does not match!.
        /// </summary>
        internal static string ActivationCodeNotMatch {
            get {
                return ResourceManager.GetString("ActivationCodeNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added successfully!.
        /// </summary>
        internal static string AddSuccessfully {
            get {
                return ResourceManager.GetString("AddSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesspoint Group in this locaiton:.
        /// </summary>
        internal static string APGInLocation {
            get {
                return ResourceManager.GetString("APGInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acesspoint in this locaiton:.
        /// </summary>
        internal static string APInLocation {
            get {
                return ResourceManager.GetString("APInLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned successfully!.
        /// </summary>
        internal static string AssignSuccessfully {
            get {
                return ResourceManager.GetString("AssignSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        internal static string ConfirmMess {
            get {
                return ResourceManager.GetString("ConfirmMess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully!.
        /// </summary>
        internal static string DeleteSuccessfully {
            get {
                return ResourceManager.GetString("DeleteSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edited successfully!.
        /// </summary>
        internal static string EditSuccessfully {
            get {
                return ResourceManager.GetString("EditSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured, please try again later..
        /// </summary>
        internal static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirming password does not match..
        /// </summary>
        internal static string InvalidConfirmPassword {
            get {
                return ResourceManager.GetString("InvalidConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload image in format &quot;.jpg&quot;/&quot;.jpeg&quot;/&quot;.png&quot;..
        /// </summary>
        internal static string InvalidImageFile {
            get {
                return ResourceManager.GetString("InvalidImageFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded file is not correct, please upload zip file..
        /// </summary>
        internal static string InvalidZipFile {
            get {
                return ResourceManager.GetString("InvalidZipFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please upload landing template..
        /// </summary>
        internal static string MissingLandingTemplateFile {
            get {
                return ResourceManager.GetString("MissingLandingTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account does not exist..
        /// </summary>
        internal static string NotExistAccount {
            get {
                return ResourceManager.GetString("NotExistAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register fail. Please try again..
        /// </summary>
        internal static string RegisterFail {
            get {
                return ResourceManager.GetString("RegisterFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register successfully! Click OK to go to home page..
        /// </summary>
        internal static string RegisterSuccessfully {
            get {
                return ResourceManager.GetString("RegisterSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed successfully!.
        /// </summary>
        internal static string RemoveSuccessfully {
            get {
                return ResourceManager.GetString("RemoveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of all clicks on Ad.
        /// </summary>
        internal static string TipClicks {
            get {
                return ResourceManager.GetString("TipClicks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clicks/Impression (% ).
        /// </summary>
        internal static string TipCTR {
            get {
                return ResourceManager.GetString("TipCTR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impressions/reach.
        /// </summary>
        internal static string TipFrequency {
            get {
                return ResourceManager.GetString("TipFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total amount of all ad views .
        /// </summary>
        internal static string TipImpression {
            get {
                return ResourceManager.GetString("TipImpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total aount of all unique visitors..
        /// </summary>
        internal static string TipReach {
            get {
                return ResourceManager.GetString("TipReach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files do not have correct format, please try again..
        /// </summary>
        internal static string WrongFormatFile {
            get {
                return ResourceManager.GetString("WrongFormatFile", resourceCulture);
            }
        }
    }
}
